#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ili9488_lvgl_example

EXTRA_COMPONENT_DIRS := $(PROJECT_PATH)components/drv
		                        #no slash here!!!

include $(IDF_PATH)/make/project.mk

